name: 06 - Contexts
run-name: 06 - Contexts | DEBUG - ${{ inputs.debug }}

on: 
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false

jobs: 
    echo-data:
        runs-on: ubuntu-latest
        steps:
            - name: Display info
              run: |
                echo "I was triggered by a ${{ github.event_name }} event."
                echo "Ref: ${{ github.ref }}"
                echo "SHA: ${{ github.sha }}"
                echo "Actor: ${{ github.actor }}"
                echo "Workflow: ${{ github.workflow }}"
                echo "run ID: ${{ github.run_id }}"
                echo "run number: ${{ github.run_number }}"
            - name: Retrieve Variable
              run: |
                echo "The value of the variable is ${{ vars.MY_VAR}}"

